version: '3.9'
services:
   app:
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 8080:8080
     depends_on:
       - db
   db:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USR
      MYSQL_PASSWORD: $MYSQL_PASS
      MYSQL_DATABASE: $MYSQL_DBNAME
    volumes:
      - ./migrations/sql/01_create_database.up.sql:/docker-entrypoint-initdb.d/01_create_database.up.sql
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
