FROM golang:1.20-alpine

WORKDIR /app

COPY . .

ENV MYSQL_DSN=${MYSQL_USR}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_CONTAINER_PORT})/${MYSQL_DBNAME}?multiStatements=true
ENV API_PORT=${API_CONTAINER_PORT}

RUN go build -o api_binary cmd/main.go

CMD ["./api_binary"]
