FROM golang:1.20-alpine

ENV MYSQL_DSN=$MYSQL_DSN
ENV API_PORT=$API_CONTAINER_PORT

WORKDIR /opt/restaurant-api
COPY . .

RUN go build -o bin/main cmd/main.go

CMD ["sh", "-c", "bin/main"]

EXPOSE $API_PORT