CREATE OR UPDATE TABLE orders (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	cliente_id BIGINT NULL,
	confirmado BOOL NOT NULL,
	pago BOOL NOT NULL,
	status_id BIGINT NOT NULL,
	criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
