apiVersion: v1
kind: Service
metadata:
  name: restaurant-api-service
  labels:
    app: restaurant-app
spec:
  selector:
    app: restaurant-api-deployament
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
