apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-mysql-pv-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
