apiVersion: v1
kind: Service
metadata:
  name: restaurant-mysql-service
  labels:
    app: restaurant-mysql
spec:
  selector:
    app: restaurant-mysql-pod
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
  type: NodePort
