name: "Restaurant CI/CD"

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "${{ vars.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "${{ vars.TF_WORKSPACE }}"
  CONFIG_DIRECTORY: "./"
  VAR_AWS_REGION: "${{vars.AWS_REGION}}"
  VAR_AWS_ACCESS_KEY: "${{secrets.AWS_ACCESS_KEY}}"
  VAR_AWS_SECRET_KEY: "${{secrets.AWS_SECRET_KEY}}"
  VAR_ECR_REPOSITORY: "${{vars.ECR_REPOSITORY}}"

jobs:
  create-docker-image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.VAR_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.VAR_AWS_SECRET_KEY }}
          aws-region: ${{vars.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$VAR_ECR_REPOSITORY:$IMAGE_TAG -t $REGISTRY/$VAR_ECR_REPOSITORY:latest .
          docker push --all-tags $REGISTRY/$VAR_ECR_REPOSITORY

